// Casework data — disputes, hardship reviews, legal-ready cases

// ---------- Disputes ----------
const DISPUTES = [
  {
    id: 'DS-1142',
    debtorId: 'D-2782',
    debtor: 'Kavitha a/p Rajendran',
    category: 'unrecognised-charge',
    categoryLabel: 'Unrecognised charge',
    amount: 1240.00,
    ccy: 'MYR',
    filed: '3 days ago',
    filedAt: '2026-05-12',
    age: 3,
    state: 'evidence-requested',
    stateLabel: 'Evidence requested',
    slaHours: 47,
    assigned: 'You',
    channel: 'whatsapp',
    summary: 'Customer claims RM 1,240 in unauthorised POS transactions on 2 May while phone was lost. Police report filed 3 May.',
    customerStatement: 'I lost my phone at KLIA on 2 May around 18:30. By the time I logged in remotely at 22:00 there were three charges I did not make totalling RM 1,240. I filed a police report at Sepang Police Station the same night (reference IPD/SEP/2026/44829). I am happy to settle the rest of my balance but I cannot pay for charges I did not make.',
    evidence: [
      { name: 'Police report IPD-SEP-2026-44829.pdf', size: '284 KB', verified: true, kind: 'doc' },
      { name: 'WhatsApp · lost phone announcement.png',  size: '142 KB', verified: true, kind: 'img' },
      { name: 'Transaction log · 02-May-2026.csv',       size: '8 KB',   verified: true, kind: 'csv' },
    ],
    timeline: [
      { at: '3 days ago · 22:14', who: 'Kavitha a/p Rajendran', what: 'Filed dispute via WhatsApp', kind: 'in' },
      { at: '3 days ago · 22:18', who: 'Vox AI',                what: 'Auto-acknowledged + requested police report', kind: 'vox' },
      { at: '2 days ago · 09:02', who: 'Kavitha a/p Rajendran', what: 'Submitted police report + transaction log', kind: 'in' },
      { at: '2 days ago · 09:14', who: 'Vox AI',                what: 'Verified police report against PDRM gateway · match', kind: 'vox' },
      { at: '2 days ago · 11:40', who: 'You',                   what: 'Opened case · contacted issuing bank fraud team', kind: 'note' },
      { at: '1 day ago · 16:22',  who: 'Maybank',               what: 'Confirmed merchant fingerprint anomaly on 2 of 3 charges', kind: 'note' },
      { at: 'In 47h',             who: 'SLA',                   what: 'Initial decision due', kind: 'sla' },
    ],
    recommendation: {
      author: 'Vox',
      decision: 'partial-uphold',
      decisionLabel: 'Uphold partially',
      amount: 980.00,
      rationale: 'Two of three disputed transactions match the fraudulent merchant fingerprint flagged by Maybank. The third was traced back to a recurring auto-renewal initiated 14 days prior to the loss — likely legitimate. Recommend waiving RM 980, keeping RM 260.',
      confidence: 0.86,
    },
  },
  {
    id: 'DS-1138',
    debtorId: 'D-2654',
    debtor: 'Siti Norzahira binti Hamid',
    category: 'billing-error',
    categoryLabel: 'Billing error',
    amount: 4280.00,
    ccy: 'MYR',
    filed: '6 days ago',
    age: 6,
    state: 'under-review',
    stateLabel: 'Under review',
    slaHours: 12,
    assigned: 'You',
    channel: 'email',
    summary: 'Customer disputes late-fee compounding. Claims one missed payment was due to a bank-side outage on 11 March; we charged 4 months of compounded penalties.',
    customerStatement: 'Your records show I missed payment in March but Maybank had a known core-banking outage that day. I tried six times. I should not be paying compound interest on something that was your partner bank\'s fault.',
    evidence: [
      { name: 'Maybank outage notice · 11-Mar-2026.pdf', size: '186 KB', verified: true, kind: 'doc' },
      { name: 'Email thread · Maybank support.eml',       size: '24 KB',  verified: true, kind: 'doc' },
    ],
    timeline: [
      { at: '6 days ago', who: 'Siti Norzahira',  what: 'Emailed disputes@dvapulse.com', kind: 'in' },
      { at: '5 days ago', who: 'You',              what: 'Acknowledged + paused collection cadence', kind: 'note' },
      { at: '3 days ago', who: 'Compliance',       what: 'Confirmed Maybank outage logged on BNM status page', kind: 'note' },
      { at: 'In 12h',     who: 'SLA',              what: 'Final decision required', kind: 'sla' },
    ],
    recommendation: {
      author: 'Vox',
      decision: 'uphold',
      decisionLabel: 'Uphold in full',
      amount: 4280,
      rationale: 'Maybank outage confirmed on BNM regulator status page. Late fees stemming from this date violate our partner-bank-outage waiver policy. Recommend full waiver + reset of compounding.',
      confidence: 0.93,
    },
  },
  {
    id: 'DS-1135',
    debtorId: 'D-2495',
    debtor: 'Datin Rohaiza binti Azman',
    category: 'service-quality',
    categoryLabel: 'Service quality',
    amount: 0,
    ccy: 'MYR',
    filed: '8 days ago',
    age: 8,
    state: 'new',
    stateLabel: 'New',
    slaHours: 71,
    assigned: 'Nor Aizan binti Malik',
    channel: 'call',
    summary: 'Customer complains about aggressive call frequency (7 calls/day) and disrespectful agent behaviour from external partner.',
    customerStatement: 'I am getting seven, eight phone calls a day from your collectors and one agent called me at 11 PM yesterday and used very rude language. I want my account back with you, not with them.',
    evidence: [
      { name: 'Call log · last 7 days.csv', size: '12 KB', verified: true, kind: 'csv' },
    ],
    timeline: [
      { at: '8 days ago', who: 'Datin Rohaiza', what: 'Complaint logged during inbound call', kind: 'in' },
      { at: '8 days ago', who: 'Vox AI',         what: 'Flagged for compliance review + paused outbound cadence', kind: 'vox' },
    ],
    recommendation: {
      author: 'Vox',
      decision: 'investigate',
      decisionLabel: 'Investigate further',
      amount: 0,
      rationale: 'Call frequency exceeded internal policy (≤3/day) on 3 of past 7 days. External partner contact was outside permitted hours (after 21:00 MYT). Recommend pulling recording + initiating partner review.',
      confidence: 0.79,
    },
  },
  {
    id: 'DS-1129',
    debtorId: 'D-2901',
    debtor: 'Mohd Ridzuan bin Zainal',
    category: 'fraud',
    categoryLabel: 'Identity fraud',
    amount: 8450.00,
    ccy: 'MYR',
    filed: '11 days ago',
    age: 11,
    state: 'resolved-upheld',
    stateLabel: 'Upheld',
    slaHours: -180,
    assigned: 'Hassan T.',
    channel: 'whatsapp',
    summary: 'Customer reported account opened in his name without consent. KYC review found MyKad mismatch.',
    evidence: [],
    timeline: [],
    recommendation: null,
  },
  {
    id: 'DS-1124',
    debtorId: 'D-2871',
    debtor: 'Nurul Aini binti Osman',
    category: 'unrecognised-charge',
    categoryLabel: 'Unrecognised charge',
    amount: 320.00,
    ccy: 'MYR',
    filed: '14 days ago',
    age: 14,
    state: 'resolved-rejected',
    stateLabel: 'Rejected',
    slaHours: -240,
    assigned: 'Hassan T.',
    channel: 'whatsapp',
    summary: 'Customer disputed a RM 320 subscription. Investigation confirmed legitimate recurring auto-debit signed up on 12 Jan.',
    evidence: [],
    timeline: [],
    recommendation: null,
  },
];

// ---------- Hardship reviews ----------
const HARDSHIP_REVIEWS = [
  {
    id: 'HR-882',
    debtorId: 'D-2782',
    debtor: 'Kavitha a/p Rajendran',
    state: 'in-review',
    stateLabel: 'In review',
    filed: '2 days ago',
    reasonCodes: ['medical-emergency', 'reduced-income'],
    severity: 'high',
    assigned: 'You',
  },
  {
    id: 'HR-878',
    debtorId: 'D-2841',
    debtor: 'Aishah binti Rahman',
    state: 'awaiting-docs',
    stateLabel: 'Awaiting documents',
    filed: '4 days ago',
    reasonCodes: ['business-cashflow'],
    severity: 'medium',
    assigned: 'You',
  },
  {
    id: 'HR-871',
    debtorId: 'D-2495',
    debtor: 'Datin Rohaiza binti Azman',
    state: 'approved',
    stateLabel: 'Approved · partial waiver',
    filed: '12 days ago',
    reasonCodes: ['business-cashflow', 'family-emergency'],
    severity: 'high',
    assigned: 'Nor Aizan binti Malik',
  },
  {
    id: 'HR-865',
    debtorId: 'D-2602',
    debtor: 'Wong Chee Kiong',
    state: 'rejected',
    stateLabel: 'Rejected',
    filed: '21 days ago',
    reasonCodes: ['business-cashflow'],
    severity: 'medium',
    assigned: 'Hassan T.',
  },
];

const HARDSHIP_REASONS = [
  { code: 'job-loss',          label: 'Job loss',                icon: 'building' },
  { code: 'reduced-income',    label: 'Reduced income',          icon: 'arrowDown' },
  { code: 'medical-emergency', label: 'Medical emergency',       icon: 'heart' },
  { code: 'family-emergency',  label: 'Family emergency',        icon: 'user' },
  { code: 'business-cashflow', label: 'Business cash-flow gap',  icon: 'building' },
  { code: 'natural-disaster',  label: 'Natural disaster',        icon: 'warn' },
  { code: 'fraud-victim',      label: 'Fraud victim',            icon: 'shield' },
  { code: 'separation',        label: 'Divorce / separation',    icon: 'user' },
];

const RELIEF_OPTIONS = [
  { code: 'payment-holiday',  label: 'Payment holiday',         desc: '30, 60 or 90-day pause · interest still accrues',         icon: 'pause' },
  { code: 'reduced-payment',  label: 'Reduced instalments',     desc: 'Lower monthly amount, longer term',                       icon: 'arrowDown' },
  { code: 'extended-term',    label: 'Extended term',           desc: 'Stretch loan duration · keep payment size',               icon: 'clock' },
  { code: 'interest-freeze',  label: 'Interest freeze',         desc: 'No additional interest for 3 / 6 months',                 icon: 'pause2' },
  { code: 'partial-waiver',   label: 'Partial waiver',          desc: 'Forgive a portion of principal or fees',                  icon: 'heart' },
  { code: 'settlement',       label: 'Full settlement discount', desc: 'Close case for a lump-sum less than balance',            icon: 'tag' },
];

// ---------- Legal-ready cases ----------
const LEGAL_QUEUE = [
  {
    id: 'LG-217',
    debtorId: 'D-2654',
    debtor: 'Siti Norzahira binti Hamid',
    ccy: 'MYR',
    balance: 45200,
    daysOverdue: 124,
    state: 'ready',
    stateLabel: 'Packet ready',
    reviewer: 'You',
    contactAttempts: 14,
    lastSuccessfulContact: '6 days ago',
    promiseAttempts: 2,
    promisesBroken: 2,
    finalNoticeSent: true,
    finalNoticeAt: '15 days ago',
    legalPartner: 'Kamarudin & Hamid Legal Associates',
    estimatedCost: 12000,
    estimatedRecovery: 32400,
  },
  {
    id: 'LG-214',
    debtorId: 'D-2602',
    debtor: 'Wong Chee Kiong',
    ccy: 'MYR',
    balance: 88300,
    daysOverdue: 102,
    state: 'checklist',
    stateLabel: 'Pre-flight checklist',
    reviewer: 'Hassan T.',
    contactAttempts: 22,
    lastSuccessfulContact: '1 week ago',
    promiseAttempts: 3,
    promisesBroken: 3,
    finalNoticeSent: true,
    finalNoticeAt: '8 days ago',
    legalPartner: null,
    estimatedCost: 18000,
    estimatedRecovery: 58400,
  },
  {
    id: 'LG-209',
    debtorId: 'D-2495',
    debtor: 'Datin Rohaiza binti Azman',
    ccy: 'MYR',
    balance: 32400,
    daysOverdue: 88,
    state: 'blocked',
    stateLabel: 'Blocked · active hardship review',
    reviewer: 'You',
    contactAttempts: 9,
    lastSuccessfulContact: '3 hours ago',
    promiseAttempts: 1,
    promisesBroken: 0,
    finalNoticeSent: false,
    legalPartner: null,
    estimatedCost: 0,
    estimatedRecovery: 0,
  },
  {
    id: 'LG-202',
    debtorId: 'D-9999',
    debtor: 'Anonymous · pending',
    ccy: 'MYR',
    balance: 24800,
    daysOverdue: 146,
    state: 'submitted',
    stateLabel: 'Submitted to legal · 4 days ago',
    reviewer: 'You',
    contactAttempts: 31,
    lastSuccessfulContact: '3 weeks ago',
    promiseAttempts: 4,
    promisesBroken: 4,
    finalNoticeSent: true,
    legalPartner: 'Tan & Associates',
    estimatedCost: 5800,
    estimatedRecovery: 18200,
  },
];

const LEGAL_PARTNERS = [
  { id: 'lp1', name: 'Kamarudin & Hamid Legal Associates', region: 'MY', specialty: 'SME recovery',         active: 18, recoveryRate: 64, avgDays: 78 },
  { id: 'lp2', name: 'Tan & Associates',                   region: 'MY', specialty: 'Consumer collection', active: 24, recoveryRate: 58, avgDays: 92 },
  { id: 'lp3', name: 'Lim, Tan & Partners',                region: 'MY', specialty: 'Commercial debt',     active: 11, recoveryRate: 71, avgDays: 64 },
  { id: 'lp4', name: 'Krishnan & Raj Law',                 region: 'MY', specialty: 'Cross-border / SME',  active:  9, recoveryRate: 51, avgDays:108 },
];

Object.assign(window, {
  DISPUTES, HARDSHIP_REVIEWS, HARDSHIP_REASONS, RELIEF_OPTIONS,
  LEGAL_QUEUE, LEGAL_PARTNERS,
});
