// Mock data for DVA Pulse — Southeast Asia debt collection scenarios

const CURRENCIES = {
  SGD: { sym: 'S$',  locale: 'en-SG', decimals: 2, flag: '🇸🇬' },
  MYR: { sym: 'RM',  locale: 'ms-MY', decimals: 2, flag: '🇲🇾' },
  IDR: { sym: 'Rp',  locale: 'id-ID', decimals: 0, flag: '🇮🇩' },
  PHP: { sym: '₱',   locale: 'en-PH', decimals: 2, flag: '🇵🇭' },
  THB: { sym: '฿',   locale: 'th-TH', decimals: 2, flag: '🇹🇭' },
  VND: { sym: '₫',   locale: 'vi-VN', decimals: 0, flag: '🇻🇳' },
};

function fmtMoney(amount, ccy = 'SGD') {
  const c = CURRENCIES[ccy] || CURRENCIES.SGD;
  const n = new Intl.NumberFormat('en-US', {
    minimumFractionDigits: c.decimals,
    maximumFractionDigits: c.decimals,
  }).format(amount);
  return `${c.sym}${n}`;
}

// Buckets for aging
function bucketOf(daysOverdue) {
  if (daysOverdue <= 0)  return { key: 'current', label: 'Current',  color: '#15803D', bg: '#ECFDF3' };
  if (daysOverdue <= 30) return { key: '1-30',    label: '1–30 days', color: '#92400E', bg: '#FEF3C7' };
  if (daysOverdue <= 60) return { key: '31-60',   label: '31–60 days', color: '#B45309', bg: '#FFEDD5' };
  if (daysOverdue <= 90) return { key: '61-90',   label: '61–90 days', color: '#C2410C', bg: '#FFE4E6' };
  return                       { key: '90+',     label: '90+ days',   color: '#9F1239', bg: '#FFE4E6' };
}

// Initials from a full name
function initials(name) {
  return name.split(/\s+/).filter(Boolean).slice(0, 2).map(s => s[0]).join('').toUpperCase();
}

// Avatar color from name
const AVATAR_COLORS = [
  ['#FFE4E6', '#9F1239'],
  ['#E0F2FE', '#075985'],
  ['#DCFCE7', '#166534'],
  ['#FEF3C7', '#92400E'],
  ['#EDE9FE', '#5B21B6'],
  ['#FCE7F3', '#9D174D'],
  ['#CFFAFE', '#155E75'],
  ['#FED7AA', '#9A3412'],
];
function avatarColor(name) {
  let h = 0;
  for (let i = 0; i < name.length; i++) h = (h * 31 + name.charCodeAt(i)) >>> 0;
  return AVATAR_COLORS[h % AVATAR_COLORS.length];
}

// ----- Debtor records -----
const DEBTORS = [
  {
    id: 'D-2841',
    name: 'Aishah binti Rahman',
    company: 'Saraswati Boutique',
    city: 'Kuala Lumpur',
    country: 'MY',
    phone: '+60 12-345 6789',
    email: 'aishah@saraswati.my',
    ccy: 'MYR',
    balance: 12450.00,
    daysOverdue: 45,
    dueDate: '2026-03-31',
    accountNumber: '4471-882-309',
    product: 'SME Working Capital Loan',
    originalAmount: 30000,
    riskScore: 64,
    promiseToPay: true,
    promiseAmount: 4150,
    promiseDate: '2026-05-22',
    assigned: 'You',
    lastContact: '2 hours ago',
    lastChannel: 'whatsapp',
    tags: ['repeat', 'sme'],
    bucket: '31-60',
    sentiment: 'cooperative',
  },
  {
    id: 'D-2839',
    name: 'Nguyễn Văn Minh',
    company: 'Minh Long Trading',
    city: 'Ho Chi Minh City',
    country: 'VN',
    phone: '+84 90 123 4567',
    email: 'minh@minhlong.vn',
    ccy: 'VND',
    balance: 18500000,
    daysOverdue: 12,
    dueDate: '2026-05-03',
    accountNumber: '8821-994-117',
    product: 'Invoice Factoring',
    originalAmount: 42000000,
    riskScore: 31,
    promiseToPay: false,
    assigned: 'You',
    lastContact: '5 hours ago',
    lastChannel: 'call',
    tags: ['first-time'],
    bucket: '1-30',
    sentiment: 'neutral',
  },
  {
    id: 'D-2782',
    name: 'Priya Subramaniam',
    company: '—',
    city: 'Singapore',
    country: 'SG',
    phone: '+65 9123 4567',
    email: 'priya.s@gmail.com',
    ccy: 'SGD',
    balance: 3890.50,
    daysOverdue: 78,
    dueDate: '2026-02-26',
    accountNumber: '0019-447-882',
    product: 'Personal Line of Credit',
    originalAmount: 8000,
    riskScore: 78,
    promiseToPay: false,
    assigned: 'You',
    lastContact: 'Yesterday',
    lastChannel: 'whatsapp',
    tags: ['hardship', 'priority'],
    bucket: '61-90',
    sentiment: 'distressed',
  },
  {
    id: 'D-2901',
    name: 'Budi Santoso',
    company: 'Warung Bintang',
    city: 'Jakarta',
    country: 'ID',
    phone: '+62 812 3456 789',
    email: 'budi.s@warungbintang.id',
    ccy: 'IDR',
    balance: 8450000,
    daysOverdue: 22,
    dueDate: '2026-04-23',
    accountNumber: '2284-101-993',
    product: 'Merchant Cash Advance',
    originalAmount: 25000000,
    riskScore: 42,
    promiseToPay: true,
    promiseAmount: 4225000,
    promiseDate: '2026-05-20',
    assigned: 'Hassan T.',
    lastContact: '3 days ago',
    lastChannel: 'sms',
    tags: ['repeat'],
    bucket: '1-30',
    sentiment: 'cooperative',
  },
  {
    id: 'D-2654',
    name: 'Maria Cristina Reyes',
    company: 'Reyes Apparel',
    city: 'Manila',
    country: 'PH',
    phone: '+63 917 234 5678',
    email: 'cristina@reyes-apparel.ph',
    ccy: 'PHP',
    balance: 45200.00,
    daysOverdue: 124,
    dueDate: '2026-01-11',
    accountNumber: '6612-883-440',
    product: 'SME Term Loan',
    originalAmount: 80000,
    riskScore: 89,
    promiseToPay: false,
    assigned: 'You',
    lastContact: '6 days ago',
    lastChannel: 'call',
    tags: ['legal-review', 'priority'],
    bucket: '90+',
    sentiment: 'avoidant',
  },
  {
    id: 'D-2933',
    name: 'Tan Wei Ming',
    company: '—',
    city: 'Singapore',
    country: 'SG',
    phone: '+65 8234 5601',
    email: 'tanwm@outlook.com',
    ccy: 'SGD',
    balance: 1250.00,
    daysOverdue: 5,
    dueDate: '2026-05-10',
    accountNumber: '0019-552-117',
    product: 'Buy Now Pay Later',
    originalAmount: 2400,
    riskScore: 18,
    promiseToPay: false,
    assigned: 'Vox AI',
    lastContact: '1 hour ago',
    lastChannel: 'vox-call',
    tags: ['first-time', 'low-risk'],
    bucket: '1-30',
    sentiment: 'cooperative',
  },
  {
    id: 'D-2778',
    name: 'Somchai Charoenpong',
    company: 'Charoen Logistics',
    city: 'Bangkok',
    country: 'TH',
    phone: '+66 81 234 5678',
    email: 's.charoen@charoenlog.th',
    ccy: 'THB',
    balance: 28400.00,
    daysOverdue: 60,
    dueDate: '2026-03-16',
    accountNumber: '7733-118-994',
    product: 'Equipment Finance',
    originalAmount: 90000,
    riskScore: 71,
    promiseToPay: true,
    promiseAmount: 9500,
    promiseDate: '2026-05-25',
    assigned: 'You',
    lastContact: '4 hours ago',
    lastChannel: 'whatsapp',
    tags: ['repeat'],
    bucket: '31-60',
    sentiment: 'neutral',
  },
  {
    id: 'D-2810',
    name: 'Lim Hui Min',
    company: '—',
    city: 'Penang',
    country: 'MY',
    phone: '+60 17-998 2410',
    email: 'huimin.lim@yahoo.com',
    ccy: 'MYR',
    balance: 6780.00,
    daysOverdue: 30,
    dueDate: '2026-04-15',
    accountNumber: '4471-770-118',
    product: 'Credit Card',
    originalAmount: 12000,
    riskScore: 52,
    promiseToPay: false,
    assigned: 'Vox AI',
    lastContact: '30 min ago',
    lastChannel: 'vox-call',
    tags: [],
    bucket: '1-30',
    sentiment: 'neutral',
  },
  {
    id: 'D-2871',
    name: 'Rina Kusuma',
    company: 'Toko Rina',
    city: 'Surabaya',
    country: 'ID',
    phone: '+62 819 8821 003',
    email: 'rina.k@tokorina.id',
    ccy: 'IDR',
    balance: 4200000,
    daysOverdue: 8,
    dueDate: '2026-05-07',
    accountNumber: '2284-552-009',
    product: 'Microloan',
    originalAmount: 10000000,
    riskScore: 24,
    promiseToPay: false,
    assigned: 'Hassan T.',
    lastContact: '2 days ago',
    lastChannel: 'whatsapp',
    tags: ['low-risk'],
    bucket: '1-30',
    sentiment: 'cooperative',
  },
  {
    id: 'D-2602',
    name: 'José Antonio Cruz',
    company: 'Cruz Hardware',
    city: 'Cebu',
    country: 'PH',
    phone: '+63 920 884 1102',
    email: 'jcruz@cruzhardware.ph',
    ccy: 'PHP',
    balance: 88300.00,
    daysOverdue: 102,
    dueDate: '2026-02-02',
    accountNumber: '6612-009-771',
    product: 'SME Term Loan',
    originalAmount: 150000,
    riskScore: 82,
    promiseToPay: false,
    assigned: 'Hassan T.',
    lastContact: '1 week ago',
    lastChannel: 'call',
    tags: ['legal-review', 'priority'],
    bucket: '90+',
    sentiment: 'avoidant',
  },
  {
    id: 'D-2950',
    name: 'Sarah binti Ismail',
    company: 'Bloom Café',
    city: 'Johor Bahru',
    country: 'MY',
    phone: '+60 13-882 1144',
    email: 'sarah@bloomcafe.my',
    ccy: 'MYR',
    balance: 2340.00,
    daysOverdue: 2,
    dueDate: '2026-05-13',
    accountNumber: '4471-118-882',
    product: 'POS Equipment Lease',
    originalAmount: 7800,
    riskScore: 15,
    promiseToPay: false,
    assigned: 'You',
    lastContact: 'Just now',
    lastChannel: 'whatsapp',
    tags: ['first-time', 'low-risk'],
    bucket: '1-30',
    sentiment: 'cooperative',
  },
  {
    id: 'D-2495',
    name: 'Trần Thị Hương',
    company: 'Huong Coffee Co.',
    city: 'Da Nang',
    country: 'VN',
    phone: '+84 93 442 1078',
    email: 'huong@huongcoffee.vn',
    ccy: 'VND',
    balance: 32400000,
    daysOverdue: 88,
    dueDate: '2026-02-16',
    accountNumber: '8821-009-114',
    product: 'SME Working Capital Loan',
    originalAmount: 120000000,
    riskScore: 76,
    promiseToPay: false,
    assigned: 'You',
    lastContact: '3 hours ago',
    lastChannel: 'call',
    tags: ['repeat', 'priority'],
    bucket: '61-90',
    sentiment: 'distressed',
  },
];

// ----- Timeline events for a debtor (the Aishah example) -----
const SAMPLE_TIMELINE = [
  {
    id: 'e12', kind: 'whatsapp', at: '2 hours ago', dir: 'in',
    title: 'WhatsApp · incoming',
    body: 'Hi, I saw your message. Cash flow is tight this month — can I pay RM 4,150 by Friday and the rest next month?',
  },
  {
    id: 'e11', kind: 'whatsapp-vox', at: '2 hours ago', dir: 'out',
    title: 'WhatsApp · Vox-drafted reply (sent by you)',
    body: 'Of course Aishah, I understand. I\'ll set up a 2-instalment plan: RM 4,150 by 22 May and RM 8,300 by 12 June. I\'ll send the confirmation shortly.',
  },
  {
    id: 'e10', kind: 'plan', at: '2 hours ago',
    title: 'Payment plan created · 2 instalments',
    body: 'RM 4,150 on 22 May 2026 · RM 8,300 on 12 June 2026',
  },
  {
    id: 'e9', kind: 'vox-call', at: 'Yesterday · 14:22', dur: '3m 14s',
    title: 'Vox autonomous reminder call',
    body: 'Vox reached Aishah; she acknowledged the balance and agreed to discuss a plan over WhatsApp.',
    sentiment: 'cooperative',
  },
  {
    id: 'e8', kind: 'whatsapp', at: '3 days ago', dir: 'out',
    title: 'WhatsApp · reminder (auto)',
    body: 'Hi Aishah, just a gentle reminder your instalment of RM 12,450 is now 42 days overdue. Reply 1 to set up a plan, 2 to chat with us.',
  },
  {
    id: 'e7', kind: 'note', at: '5 days ago', by: 'You',
    title: 'Internal note',
    body: 'Customer mentioned supplier dispute affecting cash flow. Hold legal escalation; revisit in 14 days.',
  },
  {
    id: 'e6', kind: 'sms',  at: '8 days ago', dir: 'out',
    title: 'SMS · reminder (auto)',
    body: 'DVA Pulse: Account 4471-882-309 is 34 days overdue. Pay or arrange a plan at dva.pl/pay',
  },
  {
    id: 'e5', kind: 'call', at: '12 days ago · 11:08', dur: '6m 02s', by: 'You',
    title: 'Outbound call',
    body: 'Reached Aishah. Promised to pay RM 5,000 by 30 April. Did not materialise.',
  },
  {
    id: 'e4', kind: 'payment', at: '5 weeks ago',
    title: 'Partial payment received',
    body: 'RM 2,000 via FPX bank transfer',
  },
  {
    id: 'e3', kind: 'origination', at: '14 Jan 2026',
    title: 'Loan originated',
    body: 'RM 30,000 SME working capital, 12-month term',
  },
];

// ----- WhatsApp inbox threads -----
const THREADS = [
  {
    id: 't-aishah', debtorId: 'D-2841',
    name: 'Aishah binti Rahman', preview: 'Cash flow is tight — can I pay RM 4,150 by Friday?',
    at: '2m', unread: 1, pinned: true, muted: false,
    messages: [
      { id: 'm1',  from: 'them', at: '08:14', text: 'Selamat pagi.' },
      { id: 'm2',  from: 'them', at: '08:14', text: 'I saw your message yesterday.' },
      { id: 'm3',  from: 'me',   at: '08:32', text: 'Morning Aishah 🌸 thanks for getting back. How can we help today?' },
      { id: 'm4',  from: 'them', at: '08:34', text: 'Cash flow is tight this month — can I pay RM 4,150 by Friday and the rest next month?' },
      { id: 'm5',  from: 'them', at: '08:34', text: 'I really don\'t want this to escalate, my supplier just paid late and threw everything off 😔' },
    ],
    suggestion: {
      author: 'Vox',
      text: 'Of course Aishah, I understand — supplier delays are tough. Let\'s set up a 2-instalment plan: RM 4,150 by Fri 22 May, and RM 8,300 by 12 June. I\'ll send the confirmation in a moment. Sound good?',
      tone: 'empathetic',
      rationale: 'Customer shows distress + cooperative intent. Match tone; offer concrete plan that matches their proposal; reduce escalation risk.',
    },
  },
  {
    id: 't-priya', debtorId: 'D-2782',
    name: 'Priya Subramaniam', preview: 'Can we talk tomorrow morning instead?',
    at: '14m', unread: 2, pinned: false, muted: false,
    messages: [
      { id: 'm1', from: 'them', at: '07:48', text: 'Hi, I got the notice.' },
      { id: 'm2', from: 'them', at: '07:48', text: 'Can we talk tomorrow morning instead? I\'m on shift right now.' },
    ],
    suggestion: {
      author: 'Vox',
      text: 'Absolutely Priya — what time works for you tomorrow morning? I can also send you a secure link to set up a plan online if that\'s easier 🙂',
      tone: 'empathetic',
      rationale: 'Customer wants to engage but timing-constrained. Offer flexibility + self-serve option to reduce friction.',
    },
  },
  {
    id: 't-somchai', debtorId: 'D-2778',
    name: 'Somchai Charoenpong', preview: 'Sent the slip — please confirm.',
    at: '1h', unread: 0, pinned: false, muted: false,
    messages: [
      { id: 'm1', from: 'me',   at: '09:02', text: 'Hi Somchai, just a reminder about the THB 9,500 instalment due today.' },
      { id: 'm2', from: 'them', at: '11:48', text: 'Paid this morning.' },
      { id: 'm3', from: 'them', at: '11:48', text: '[Payment slip · CharoenLog_20260515.pdf]', attachment: 'pdf' },
      { id: 'm4', from: 'them', at: '11:49', text: 'Sent the slip — please confirm.' },
    ],
    suggestion: {
      author: 'Vox',
      text: 'Got it, Somchai — slip received and matched against the instalment. Confirmation receipt #PMT-9821 sent to your email. Thanks for keeping it on schedule 🙏',
      tone: 'warm',
      rationale: 'Customer fulfilled commitment. Confirm receipt promptly to reinforce trust + provide reference number.',
    },
  },
  {
    id: 't-rina', debtorId: 'D-2871',
    name: 'Rina Kusuma', preview: 'Terima kasih, sudah saya catat.',
    at: '3h', unread: 0, pinned: false, muted: false,
    messages: [
      { id: 'm1', from: 'me',   at: '06:30', text: 'Selamat pagi Bu Rina, instalment Rp 1,400,000 jatuh tempo 22 Mei ya. Bisa dibantu transfer sebelumnya?' },
      { id: 'm2', from: 'them', at: '06:42', text: 'Terima kasih, sudah saya catat. Insya Allah tanggal 20 sudah saya transfer.' },
    ],
    suggestion: null,
  },
  {
    id: 't-budi', debtorId: 'D-2901',
    name: 'Budi Santoso', preview: 'Boleh besok pagi?', at: 'Yesterday', unread: 0, pinned: false, muted: false,
    messages: [],
    suggestion: null,
  },
  {
    id: 't-sarah', debtorId: 'D-2950',
    name: 'Sarah binti Ismail', preview: 'Done — receipt attached.', at: 'Yesterday', unread: 0, pinned: false, muted: false,
    messages: [],
    suggestion: null,
  },
  {
    id: 't-cristina', debtorId: 'D-2654',
    name: 'Maria Cristina Reyes', preview: 'No response · last seen 6 days ago', at: '6d', unread: 0, pinned: false, muted: true,
    messages: [],
    suggestion: null,
  },
];

// ----- Agents / team -----
const AGENTS = [
  { id: 'a1', name: 'You (Farah A.)',     role: 'Senior Collection Agent', region: 'MY/SG', online: true,  active: 28, resolved: 14, collected: 84200, hours: 6.5 },
  { id: 'a2', name: 'Hassan Tjahaja',     role: 'Collection Agent',        region: 'ID',    online: true,  active: 32, resolved: 11, collected: 62300, hours: 7.2 },
  { id: 'a3', name: 'Linh Pham',          role: 'Collection Agent',        region: 'VN',    online: true,  active: 24, resolved: 9,  collected: 41800, hours: 6.0 },
  { id: 'a4', name: 'Jonas dela Cruz',    role: 'Senior Collection Agent', region: 'PH',    online: false, active: 31, resolved: 12, collected: 71200, hours: 7.8 },
  { id: 'a5', name: 'Apinya Suthorn',     role: 'Collection Agent',        region: 'TH',    online: true,  active: 19, resolved: 8,  collected: 38400, hours: 5.4 },
  { id: 'a6', name: 'Vox AI · cohort #1', role: 'Autonomous AI agent',     region: 'All',   online: true,  active: 412, resolved: 188, collected: 224800, hours: 24, isAi: true },
];

// ----- KPIs for report dashboard -----
const KPIS = {
  collectedThisMonth: 1284500,   // SGD-equivalent
  collectedDelta: 18.4,          // % vs last month
  recoveryRate: 67.2,            // %
  recoveryDelta: 4.1,
  promiseToPayRate: 42.8,        // %
  promiseDelta: -2.3,
  ptpKept: 81.4,                 // %
  ptpKeptDelta: 3.6,
  avgDaysToResolve: 11.3,
  avgDaysDelta: -1.8,
  voxResolutionShare: 28.0,
  voxDelta: 6.4,
};

const RECOVERY_BY_BUCKET = [
  { bucket: 'Current',  amount: 412000, recovered: 384200 },
  { bucket: '1–30',     amount: 318400, recovered: 261100 },
  { bucket: '31–60',    amount: 188200, recovered: 119300 },
  { bucket: '61–90',    amount:  98700, recovered:  41200 },
  { bucket: '90+',      amount: 124800, recovered:  28400 },
];

const CHANNEL_PERF = [
  { channel: 'WhatsApp',   reach: 92, resolve: 41, color: '#25D366' },
  { channel: 'Vox AI call', reach: 78, resolve: 34, color: '#00B8D9' },
  { channel: 'Agent call', reach: 64, resolve: 52, color: '#E11D48' },
  { channel: 'SMS',        reach: 88, resolve: 12, color: '#A1A1AA' },
  { channel: 'Email',      reach: 71, resolve:  9, color: '#6B7280' },
];

// expose globally
Object.assign(window, {
  CURRENCIES, fmtMoney, bucketOf, initials, avatarColor,
  DEBTORS, SAMPLE_TIMELINE, THREADS, AGENTS, KPIS,
  RECOVERY_BY_BUCKET, CHANNEL_PERF,
});
